### ISSUE TITLE
您好，代码里的Q1和Q2是什么意思了

### ISSUE THREAD

**Issue by ybxgood** [zhengzhao97/Louvain#1]
您好，代码里的Q1和Q2是什么意思了，和公式对应不起来，麻烦您给解释一下

**Comment by Woodstock-z** [comment]
您好，感谢您的提问。
根据论文原文，合并节点后模块的变化ΔQ由两部组成，分别是“将该节点移除社区带来的模块度变化（Q1）”和“将节点加入其邻居所在的社区所带来的模块度变化（Q2）”。
与论文公式不对应的原因是因为论文中给出的公式描述的是将isolated 节点移入社区C带来的模块度增益（moving an isolated node i into a  ommunity C can easily be computed by xx）。
如有解释不清，欢迎回复！

**Comment by ybxgood** [comment]
您好，可否加下我QQ 聊一下：1903961334
